# print("Products Table")
# print("\n")
# print("11 - Almond Joy Candy Bar. - $1.25")
# print("12 - Twix Candy Bars. - $3.50")
# print("13 - Reese's Peanut Butter Cups. - $1.75")
# print("21 - Heath Bar. - $2.25")
# print("22 - 100 Grand Bar. - $0.25")
# print("23 - Kit Kat Candy Bar. - $1.25")
# print("31 - Butterfinger. - $0.75")
# print("32 - 5th Avenue Candy Bar. - $4.50")
# print("33 - Hershey's. - $3.25")
# print("\n")
# print("----------------")
# print("| 11 | 12 | 13 |")
# print("| 21 | 22 | 23 |")
# print("| 31 | 32 | 33 |")
# print("================")
# print("|    ------    |")
# print("================")
# print("\n")

# product = ""

# while  product != "11" and product != "12" and product != "13" and product != "21" and product != "22" and product != "23" and product != "31" and product != "32" and product != "33":
#     product = input("Choose your product: ")
